---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  AZ_1_CUSTER_NAME:
  AZ_1_RP_NAME:


inputs:
  #- name: concourse-vsphere
  - name: nhc
  - name: govc
  
run:
  path: ./nhc/tasks/vsphere/install-nhc/task.sh
