pivnet_token: Z-ugVAzNsGd2bUoWb8si
github_token: 6551d3b80358c9af83985337b69c4241e5da670d

vcenter_host: nhc-ext-vcs.customer.local
vcenter_usr: solarch@vsphere.local
vcenter_pwd: password
vcenter_data_center: NHC

vm_disk_type: thin
ephemeral_storage_names: MARVIN-Virtual-SAN-Datastore-6b11ec3b-904e-4435-a21d-9b213a88eda9
persistent_storage_names: MARVIN-Virtual-SAN-Datastore-6b11ec3b-904e-4435-a21d-9b213a88eda9

ntp_servers: 10.228.118.32,10.228.118.33
infra_vsphere_network: pg_vxrail05_2510
infra_nw_cidr: 172.20.241.0/24
infra_nw_dns: 10.228.118.32,10.228.118.33
infra_nw_gateway: 172.20.241.62


az_1_cluster_name: vxrail06-CL
az_1_rp_name: SolArch

nhc-release: 2.0 
s3-bucket: hari-poc
s3-access-key-id: haripoc
s3-secret-access-key: 4TX/PXu3BOz3mOBXcYJtqcpIInmUvXx+rhwZfZ8/
ecs-endpoint: http://172.20.241.67:9020
s3_region: US
