resources:
- name: minio-s3
  type: s3
  source:
    regexp: example-file-(.*).txt
    endpoint: {{ecs-endpoint}}
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    disable_ssl: true
- name: nhc
  type: s3
  source:
    regexp: om-linux-(.*)
    endpoint: {{ecs-endpoint}}
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    disable_ssl: true


jobs:
- name: minio-s3-write-it-out
  plan:
  - task: cat-example-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: bash
        args:
        - -c
        - echo "This is an example file, created $(date)" > file-to-upload/example-file-1.txt
      outputs:
        - name: file-to-upload
  - put: minio-s3
    params:
      file: file-to-upload/example-file-*

- name: minio-s3-read-it-out
  plan:
  - get: minio-s3
  - get: nhc
  - task: cat-example-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
      - name: minio-s3
      run:
        path: bash
        args:
        - -c
        - cat minio-s3/example-file-*
